openapi: 3.0.0
info:
  title: back
  version: 0.0.0

servers:
  - url: http://examplp.com/api/

paths:
  /users:
    get:
      summary: Get all user data
      parameters: []
      responses:
        '200':
          description:  A JSON array of User model
          content:
            application/json:
              schema:
                type: array
                items:
                $ref: '#/components/schemas/User'

  /users/{userName}:
    get:
      summary: Get user data
      parameters: []
      responses:
        '200':
          description: A JSON object of user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'



components:
  schemas:
    User:
      type: object
      required:
        - id
      properties:
        name:
            type: string
        point:
          type: integer
          format: int64



